<?php

use Illuminate\Database\Seeder;
use App\CarModels;

class CarModelsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cars = [
            ['brand_id' => ' 1', 'model' => ' CL'],
            ['brand_id' => ' 1', 'model' => ' EL'],
            ['brand_id' => ' 1', 'model' => ' ILX'],
            ['brand_id' => ' 1', 'model' => ' Integra'],
            ['brand_id' => ' 1', 'model' => ' MDX'],
            ['brand_id' => ' 1', 'model' => ' NSX'],
            ['brand_id' => ' 1', 'model' => ' RDX'],
            ['brand_id' => ' 1', 'model' => ' RL'],
            ['brand_id' => ' 1', 'model' => ' RSX'],
            ['brand_id' => ' 1', 'model' => ' TL'],
            ['brand_id' => ' 1', 'model' => ' TLX'],
            ['brand_id' => ' 1', 'model' => ' TSX'],
            ['brand_id' => ' 1', 'model' => ' ZDX'],
            ['brand_id' => ' 2', 'model' => ' 146'],
            ['brand_id' => ' 2', 'model' => ' 147'],
            ['brand_id' => ' 2', 'model' => ' 147 GTA'],
            ['brand_id' => ' 2', 'model' => ' 156'],
            ['brand_id' => ' 2', 'model' => ' 156 GTA'],
            ['brand_id' => ' 2', 'model' => ' 159'],
            ['brand_id' => ' 2', 'model' => ' 166'],
            ['brand_id' => ' 2', 'model' => ' 4C'],
            ['brand_id' => ' 2', 'model' => ' 8C Competizione'],
            ['brand_id' => ' 2', 'model' => ' Brera'],
            ['brand_id' => ' 2', 'model' => ' C-SUV'],
            ['brand_id' => ' 2', 'model' => ' Giulia'],
            ['brand_id' => ' 2', 'model' => ' Giulietta'],
            ['brand_id' => ' 2', 'model' => ' GT'],
            ['brand_id' => ' 2', 'model' => ' GTV'],
            ['brand_id' => ' 2', 'model' => ' MiTo'],
            ['brand_id' => ' 2', 'model' => ' Spider'],
            ['brand_id' => ' 2', 'model' => ' Stelvio'],
            ['brand_id' => ' 3', 'model' => ' Cygnet'],
            ['brand_id' => ' 3', 'model' => ' DB11'],
            ['brand_id' => ' 3', 'model' => ' DB9'],
            ['brand_id' => ' 3', 'model' => ' DBS'],
            ['brand_id' => ' 3', 'model' => ' DBS Violante'],
            ['brand_id' => ' 3', 'model' => ' Rapide'],
            ['brand_id' => ' 3', 'model' => ' V12 Vantage'],
            ['brand_id' => ' 3', 'model' => ' V8 Vantage'],
            ['brand_id' => ' 3', 'model' => ' Vanquish'],
            ['brand_id' => ' 3', 'model' => ' Vanquish (VH)'],
            ['brand_id' => ' 3', 'model' => ' Virage'],
            ['brand_id' => ' 3', 'model' => ' Zagato Coupe'],
            ['brand_id' => ' 4', 'model' => ' A1'],
            ['brand_id' => ' 4', 'model' => ' A2'],
            ['brand_id' => ' 4', 'model' => ' A3'],
            ['brand_id' => ' 4', 'model' => ' A4'],
            ['brand_id' => ' 4', 'model' => ' A4 Allroad Quattro'],
            ['brand_id' => ' 4', 'model' => ' A5'],
            ['brand_id' => ' 4', 'model' => ' A6'],
            ['brand_id' => ' 4', 'model' => ' A7'],
            ['brand_id' => ' 4', 'model' => ' A8'],
            ['brand_id' => ' 4', 'model' => ' Allroad'],
            ['brand_id' => ' 4', 'model' => ' Q2'],
            ['brand_id' => ' 4', 'model' => ' Q3'],
            ['brand_id' => ' 4', 'model' => ' Q5'],
            ['brand_id' => ' 4', 'model' => ' Q7'],
            ['brand_id' => ' 4', 'model' => ' R8'],
            ['brand_id' => ' 4', 'model' => ' RS Q3'],
            ['brand_id' => ' 4', 'model' => ' RS3'],
            ['brand_id' => ' 4', 'model' => ' RS4'],
            ['brand_id' => ' 4', 'model' => ' RS6'],
            ['brand_id' => ' 4', 'model' => ' RS7'],
            ['brand_id' => ' 4', 'model' => ' S3'],
            ['brand_id' => ' 4', 'model' => ' S4'],
            ['brand_id' => ' 4', 'model' => ' S5'],
            ['brand_id' => ' 4', 'model' => ' S6'],
            ['brand_id' => ' 4', 'model' => ' S7'],
            ['brand_id' => ' 4', 'model' => ' S8'],
            ['brand_id' => ' 4', 'model' => ' TT'],
            ['brand_id' => ' 4', 'model' => ' TT RS'],
            ['brand_id' => ' 4', 'model' => ' TTS'],
            ['brand_id' => ' 5', 'model' => ' Arnage'],
            ['brand_id' => ' 5', 'model' => ' Azure'],
            ['brand_id' => ' 5', 'model' => ' Bentayga'],
            ['brand_id' => ' 5', 'model' => ' Brooklands'],
            ['brand_id' => ' 5', 'model' => ' Continental'],
            ['brand_id' => ' 5', 'model' => ' Mulsanne'],
            ['brand_id' => ' 6', 'model' => ' 1 series'],
            ['brand_id' => ' 6', 'model' => ' 2 series'],
            ['brand_id' => ' 6', 'model' => ' 3 series'],
            ['brand_id' => ' 6', 'model' => ' 4 series'],
            ['brand_id' => ' 6', 'model' => ' 5 series'],
            ['brand_id' => ' 6', 'model' => ' 6 series'],
            ['brand_id' => ' 6', 'model' => ' 7 series'],
            ['brand_id' => ' 6', 'model' => ' 8 series'],
            ['brand_id' => ' 6', 'model' => ' i3'],
            ['brand_id' => ' 6', 'model' => ' i8'],
            ['brand_id' => ' 6', 'model' => ' M3'],
            ['brand_id' => ' 6', 'model' => ' M4'],
            ['brand_id' => ' 6', 'model' => ' M5'],
            ['brand_id' => ' 6', 'model' => ' M6'],
            ['brand_id' => ' 6', 'model' => ' X1'],
            ['brand_id' => ' 6', 'model' => ' X3'],
            ['brand_id' => ' 6', 'model' => ' X4'],
            ['brand_id' => ' 6', 'model' => ' X5'],
            ['brand_id' => ' 6', 'model' => ' X5 M'],
            ['brand_id' => ' 6', 'model' => ' X6'],
            ['brand_id' => ' 6', 'model' => ' X6 M'],
            ['brand_id' => ' 6', 'model' => ' Z3'],
            ['brand_id' => ' 6', 'model' => ' Z4'],
            ['brand_id' => ' 6', 'model' => ' Z8'],
            ['brand_id' => ' 7', 'model' => ' Century'],
            ['brand_id' => ' 7', 'model' => ' Enclave'],
            ['brand_id' => ' 7', 'model' => ' Envision'],
            ['brand_id' => ' 7', 'model' => ' La Crosse'],
            ['brand_id' => ' 7', 'model' => ' Le Sabre'],
            ['brand_id' => ' 7', 'model' => ' Lucerne'],
            ['brand_id' => ' 7', 'model' => ' Park Avenue'],
            ['brand_id' => ' 7', 'model' => ' Rainier'],
            ['brand_id' => ' 7', 'model' => ' Regal'],
            ['brand_id' => ' 7', 'model' => ' Rendezvouz'],
            ['brand_id' => ' 7', 'model' => ' Terraza'],
            ['brand_id' => ' 7', 'model' => ' Verano'],
            ['brand_id' => ' 8', 'model' => ' ATS'],
            ['brand_id' => ' 8', 'model' => ' BLS'],
            ['brand_id' => ' 8', 'model' => ' CT6'],
            ['brand_id' => ' 8', 'model' => ' CTS'],
            ['brand_id' => ' 8', 'model' => ' De Ville'],
            ['brand_id' => ' 8', 'model' => ' DTS'],
            ['brand_id' => ' 8', 'model' => ' Eldorado'],
            ['brand_id' => ' 8', 'model' => ' Escalade'],
            ['brand_id' => ' 8', 'model' => ' Seville'],
            ['brand_id' => ' 8', 'model' => ' SRX'],
            ['brand_id' => ' 8', 'model' => ' STS'],
            ['brand_id' => ' 8', 'model' => ' XLR'],
            ['brand_id' => ' 8', 'model' => ' XT5'],
            ['brand_id' => ' 8', 'model' => ' XTS'],
            ['brand_id' => ' 9', 'model' => ' Amulet'],
            ['brand_id' => ' 9', 'model' => ' Arrizo 7'],
            ['brand_id' => ' 9', 'model' => ' Bonus'],
            ['brand_id' => ' 9', 'model' => ' Bonus 3'],
            ['brand_id' => ' 9', 'model' => ' CrossEastar'],
            ['brand_id' => ' 9', 'model' => ' Eastar'],
            ['brand_id' => ' 9', 'model' => ' Fora'],
            ['brand_id' => ' 9', 'model' => ' IndiS'],
            ['brand_id' => ' 9', 'model' => ' Kimo'],
            ['brand_id' => ' 9', 'model' => ' M11'],
            ['brand_id' => ' 9', 'model' => ' QQ'],
            ['brand_id' => ' 9', 'model' => ' QQ6'],
            ['brand_id' => ' 9', 'model' => ' Tiggo'],
            ['brand_id' => ' 9', 'model' => ' Tiggo 5'],
            ['brand_id' => ' 9', 'model' => ' Very'],
            ['brand_id' => ' 10', 'model' => ' Astro'],
            ['brand_id' => ' 10', 'model' => ' Avalanche'],
            ['brand_id' => ' 10', 'model' => ' Aveo'],
            ['brand_id' => ' 10', 'model' => ' Blazer'],
            ['brand_id' => ' 10', 'model' => ' Camaro'],
            ['brand_id' => ' 10', 'model' => ' Captiva'],
            ['brand_id' => ' 10', 'model' => ' Cavalier'],
            ['brand_id' => ' 10', 'model' => ' Cobalt'],
            ['brand_id' => ' 10', 'model' => ' Colorado'],
            ['brand_id' => ' 10', 'model' => ' Corvette'],
            ['brand_id' => ' 10', 'model' => ' Cruze'],
            ['brand_id' => ' 10', 'model' => ' Epica'],
            ['brand_id' => ' 10', 'model' => ' Equinox'],
            ['brand_id' => ' 10', 'model' => ' Express'],
            ['brand_id' => ' 10', 'model' => ' HHR'],
            ['brand_id' => ' 10', 'model' => ' Impala'],
            ['brand_id' => ' 10', 'model' => ' Lacetti'],
            ['brand_id' => ' 10', 'model' => ' Lanos'],
            ['brand_id' => ' 10', 'model' => ' Malibu'],
            ['brand_id' => ' 10', 'model' => ' Monte Carlo'],
            ['brand_id' => ' 10', 'model' => ' Niva'],
            ['brand_id' => ' 10', 'model' => ' Orlando'],
            ['brand_id' => ' 10', 'model' => ' Rezzo'],
            ['brand_id' => ' 10', 'model' => ' Silverado'],
            ['brand_id' => ' 10', 'model' => ' Spark'],
            ['brand_id' => ' 10', 'model' => ' SSR'],
            ['brand_id' => ' 10', 'model' => ' Suburban'],
            ['brand_id' => ' 10', 'model' => ' Tahoe'],
            ['brand_id' => ' 10', 'model' => ' TrailBlazer'],
            ['brand_id' => ' 10', 'model' => ' Traverse'],
            ['brand_id' => ' 10', 'model' => ' Trax'],
            ['brand_id' => ' 10', 'model' => ' Uplander'],
            ['brand_id' => ' 10', 'model' => ' Venture'],
            ['brand_id' => ' 11', 'model' => ' 300C'],
            ['brand_id' => ' 11', 'model' => ' 300M'],
            ['brand_id' => ' 11', 'model' => ' Aspen'],
            ['brand_id' => ' 11', 'model' => ' Concorde'],
            ['brand_id' => ' 11', 'model' => ' Crossfire'],
            ['brand_id' => ' 11', 'model' => ' Grand Voyager'],
            ['brand_id' => ' 11', 'model' => ' Pacifica'],
            ['brand_id' => ' 11', 'model' => ' PT Cruiser'],
            ['brand_id' => ' 11', 'model' => ' Sebring'],
            ['brand_id' => ' 11', 'model' => ' Town & Country'],
            ['brand_id' => ' 11', 'model' => ' Voyager'],
            ['brand_id' => ' 12', 'model' => ' Berlingo'],
            ['brand_id' => ' 12', 'model' => ' C-Crosser'],
            ['brand_id' => ' 12', 'model' => ' C-Elysee'],
            ['brand_id' => ' 12', 'model' => ' C1'],
            ['brand_id' => ' 12', 'model' => ' C2'],
            ['brand_id' => ' 12', 'model' => ' C3'],
            ['brand_id' => ' 12', 'model' => ' C3 Picasso'],
            ['brand_id' => ' 12', 'model' => ' C3 Pluriel'],
            ['brand_id' => ' 12', 'model' => ' C4'],
            ['brand_id' => ' 12', 'model' => ' C4 Aircross'],
            ['brand_id' => ' 12', 'model' => ' C4 Cactus'],
            ['brand_id' => ' 12', 'model' => ' C4 Picasso'],
            ['brand_id' => ' 12', 'model' => ' C5'],
            ['brand_id' => ' 12', 'model' => ' C6'],
            ['brand_id' => ' 12', 'model' => ' C8'],
            ['brand_id' => ' 12', 'model' => ' DS3'],
            ['brand_id' => ' 12', 'model' => ' DS4'],
            ['brand_id' => ' 12', 'model' => ' DS5'],
            ['brand_id' => ' 12', 'model' => ' Grand C4 Picasso'],
            ['brand_id' => ' 12', 'model' => ' Jumpy'],
            ['brand_id' => ' 12', 'model' => ' Nemo'],
            ['brand_id' => ' 12', 'model' => ' Saxo'],
            ['brand_id' => ' 12', 'model' => ' Spacetourer'],
            ['brand_id' => ' 12', 'model' => ' Xsara'],
            ['brand_id' => ' 12', 'model' => ' Xsara Picasso'],
            ['brand_id' => ' 13', 'model' => ' Evanda'],
            ['brand_id' => ' 13', 'model' => ' Kalos'],
            ['brand_id' => ' 13', 'model' => ' Leganza'],
            ['brand_id' => ' 13', 'model' => ' Magnus'],
            ['brand_id' => ' 13', 'model' => ' Matiz'],
            ['brand_id' => ' 13', 'model' => ' Nexia'],
            ['brand_id' => ' 13', 'model' => ' Nubira'],
            ['brand_id' => ' 14', 'model' => ' Applause'],
            ['brand_id' => ' 14', 'model' => ' Copen'],
            ['brand_id' => ' 14', 'model' => ' Cuore'],
            ['brand_id' => ' 14', 'model' => ' Gran Move'],
            ['brand_id' => ' 14', 'model' => ' Materia'],
            ['brand_id' => ' 14', 'model' => ' Sirion'],
            ['brand_id' => ' 14', 'model' => ' Terios'],
            ['brand_id' => ' 14', 'model' => ' Trevis'],
            ['brand_id' => ' 14', 'model' => ' YRV'],
            ['brand_id' => ' 15', 'model' => ' Avenger'],
            ['brand_id' => ' 15', 'model' => ' Caliber'],
            ['brand_id' => ' 15', 'model' => ' Caliber SRT4'],
            ['brand_id' => ' 15', 'model' => ' Caravan'],
            ['brand_id' => ' 15', 'model' => ' Charger'],
            ['brand_id' => ' 15', 'model' => ' Dakota'],
            ['brand_id' => ' 15', 'model' => ' Durango'],
            ['brand_id' => ' 15', 'model' => ' Intrepid'],
            ['brand_id' => ' 15', 'model' => ' Journey'],
            ['brand_id' => ' 15', 'model' => ' Magnum'],
            ['brand_id' => ' 15', 'model' => ' Neon'],
            ['brand_id' => ' 15', 'model' => ' Nitro'],
            ['brand_id' => ' 15', 'model' => ' Ram 1500'],
            ['brand_id' => ' 15', 'model' => ' Ram 2500'],
            ['brand_id' => ' 15', 'model' => ' Ram SRT10'],
            ['brand_id' => ' 15', 'model' => ' Stratus'],
            ['brand_id' => ' 15', 'model' => ' Viper'],
            ['brand_id' => ' 15', 'model' => ' Viper V'],
            ['brand_id' => ' 16', 'model' => ' Besturn B50'],
            ['brand_id' => ' 16', 'model' => ' Vita'],
            ['brand_id' => ' 17', 'model' => ' 348 GT'],
            ['brand_id' => ' 17', 'model' => ' 348 Spider'],
            ['brand_id' => ' 17', 'model' => ' 360 Modena'],
            ['brand_id' => ' 17', 'model' => ' 360 Spider'],
            ['brand_id' => ' 17', 'model' => ' 456 GT'],
            ['brand_id' => ' 17', 'model' => ' 456 GTA'],
            ['brand_id' => ' 17', 'model' => ' 456 M GT'],
            ['brand_id' => ' 17', 'model' => ' 456 M GTA'],
            ['brand_id' => ' 17', 'model' => ' 458 Italia'],
            ['brand_id' => ' 17', 'model' => ' 488 GTB'],
            ['brand_id' => ' 17', 'model' => ' 512 TR'],
            ['brand_id' => ' 17', 'model' => ' 550 Barchetta Pininfarina'],
            ['brand_id' => ' 17', 'model' => ' 550 Maranello'],
            ['brand_id' => ' 17', 'model' => ' 575 M Maranello'],
            ['brand_id' => ' 17', 'model' => ' 599 GTB Fiorano'],
            ['brand_id' => ' 17', 'model' => ' 599 GTO'],
            ['brand_id' => ' 17', 'model' => ' 612 Scaglietti'],
            ['brand_id' => ' 17', 'model' => ' California'],
            ['brand_id' => ' 17', 'model' => ' California T'],
            ['brand_id' => ' 17', 'model' => ' Challenge Stradale'],
            ['brand_id' => ' 17', 'model' => ' Enzo'],
            ['brand_id' => ' 17', 'model' => ' F12 Berlinetta'],
            ['brand_id' => ' 17', 'model' => ' F355'],
            ['brand_id' => ' 17', 'model' => ' F430'],
            ['brand_id' => ' 17', 'model' => ' F50'],
            ['brand_id' => ' 17', 'model' => ' F512 M'],
            ['brand_id' => ' 17', 'model' => ' FF'],
            ['brand_id' => ' 17', 'model' => ' FXX'],
            ['brand_id' => ' 17', 'model' => ' Superamerica'],
            ['brand_id' => ' 18', 'model' => ' 500'],
            ['brand_id' => ' 18', 'model' => ' 500L'],
            ['brand_id' => ' 18', 'model' => ' Albea'],
            ['brand_id' => ' 18', 'model' => ' Brava'],
            ['brand_id' => ' 18', 'model' => ' Bravo'],
            ['brand_id' => ' 18', 'model' => ' Coupe'],
            ['brand_id' => ' 18', 'model' => ' Croma'],
            ['brand_id' => ' 18', 'model' => ' Doblo'],
            ['brand_id' => ' 18', 'model' => ' DuСЃato'],
            ['brand_id' => ' 18', 'model' => ' Grande Punto'],
            ['brand_id' => ' 18', 'model' => ' Idea'],
            ['brand_id' => ' 18', 'model' => ' Linea'],
            ['brand_id' => ' 18', 'model' => ' Marea'],
            ['brand_id' => ' 18', 'model' => ' Multipla'],
            ['brand_id' => ' 18', 'model' => ' Palio'],
            ['brand_id' => ' 18', 'model' => ' Panda'],
            ['brand_id' => ' 18', 'model' => ' Panda 4x4'],
            ['brand_id' => ' 18', 'model' => ' Punto'],
            ['brand_id' => ' 18', 'model' => ' Qubo'],
            ['brand_id' => ' 18', 'model' => ' Sedici'],
            ['brand_id' => ' 18', 'model' => ' Stilo'],
            ['brand_id' => ' 18', 'model' => ' Ulysse'],
            ['brand_id' => ' 19', 'model' => ' B-Max'],
            ['brand_id' => ' 19', 'model' => ' C-Max'],
            ['brand_id' => ' 19', 'model' => ' Cougar'],
            ['brand_id' => ' 19', 'model' => ' Crown Victoria'],
            ['brand_id' => ' 19', 'model' => ' EcoSport'],
            ['brand_id' => ' 19', 'model' => ' Edge'],
            ['brand_id' => ' 19', 'model' => ' Escape'],
            ['brand_id' => ' 19', 'model' => ' Excursion'],
            ['brand_id' => ' 19', 'model' => ' Expedition'],
            ['brand_id' => ' 19', 'model' => ' Explorer'],
            ['brand_id' => ' 19', 'model' => ' F-150'],
            ['brand_id' => ' 19', 'model' => ' Fiesta'],
            ['brand_id' => ' 19', 'model' => ' Five Hundred'],
            ['brand_id' => ' 19', 'model' => ' Flex'],
            ['brand_id' => ' 19', 'model' => ' Focus'],
            ['brand_id' => ' 19', 'model' => ' Freestar'],
            ['brand_id' => ' 19', 'model' => ' Freestyle'],
            ['brand_id' => ' 19', 'model' => ' Fusion'],
            ['brand_id' => ' 19', 'model' => ' Galaxy'],
            ['brand_id' => ' 19', 'model' => ' Ka'],
            ['brand_id' => ' 19', 'model' => ' Kuga'],
            ['brand_id' => ' 19', 'model' => ' Maverick'],
            ['brand_id' => ' 19', 'model' => ' Mondeo'],
            ['brand_id' => ' 19', 'model' => ' Mustang'],
            ['brand_id' => ' 19', 'model' => ' Puma'],
            ['brand_id' => ' 19', 'model' => ' Ranger'],
            ['brand_id' => ' 19', 'model' => ' S-Max'],
            ['brand_id' => ' 19', 'model' => ' Sport Trac'],
            ['brand_id' => ' 19', 'model' => ' Taurus'],
            ['brand_id' => ' 19', 'model' => ' Taurus X'],
            ['brand_id' => ' 19', 'model' => ' Thunderbird'],
            ['brand_id' => ' 19', 'model' => ' Tourneo Connect'],
            ['brand_id' => ' 19', 'model' => ' Transit'],
            ['brand_id' => ' 19', 'model' => ' Transit Connect'],
            ['brand_id' => ' 20', 'model' => ' Emgrand EC7'],
            ['brand_id' => ' 20', 'model' => ' Emgrand X7'],
            ['brand_id' => ' 20', 'model' => ' GРЎ6'],
            ['brand_id' => ' 20', 'model' => ' MK'],
            ['brand_id' => ' 20', 'model' => ' Otaka'],
            ['brand_id' => ' 20', 'model' => ' Vision'],
            ['brand_id' => ' 21', 'model' => ' Acadia'],
            ['brand_id' => ' 21', 'model' => ' Canyon'],
            ['brand_id' => ' 21', 'model' => ' Envoy'],
            ['brand_id' => ' 21', 'model' => ' Sierra 1500'],
            ['brand_id' => ' 21', 'model' => ' Sierra 2500'],
            ['brand_id' => ' 21', 'model' => ' Yukon'],
            ['brand_id' => ' 22', 'model' => ' Cowry'],
            ['brand_id' => ' 22', 'model' => ' Deer'],
            ['brand_id' => ' 22', 'model' => ' GWPeri'],
            ['brand_id' => ' 22', 'model' => ' Hover'],
            ['brand_id' => ' 22', 'model' => ' Hover H5'],
            ['brand_id' => ' 22', 'model' => ' Pegasus'],
            ['brand_id' => ' 22', 'model' => ' Safe'],
            ['brand_id' => ' 22', 'model' => ' Sailor'],
            ['brand_id' => ' 22', 'model' => ' Sing'],
            ['brand_id' => ' 22', 'model' => ' Socool'],
            ['brand_id' => ' 22', 'model' => ' Wingle'],
            ['brand_id' => ' 23', 'model' => ' Accord'],
            ['brand_id' => ' 23', 'model' => ' Accord IX (CZ)'],
            ['brand_id' => ' 23', 'model' => ' Civic'],
            ['brand_id' => ' 23', 'model' => ' Civic IX (FB, FG)'],
            ['brand_id' => ' 23', 'model' => ' Civic X (FC)'],
            ['brand_id' => ' 23', 'model' => ' CR-V'],
            ['brand_id' => ' 23', 'model' => ' CR-Z (ZF1)'],
            ['brand_id' => ' 23', 'model' => ' Crosstour'],
            ['brand_id' => ' 23', 'model' => ' Element'],
            ['brand_id' => ' 23', 'model' => ' Fit'],
            ['brand_id' => ' 23', 'model' => ' FR-V'],
            ['brand_id' => ' 23', 'model' => ' HR-V'],
            ['brand_id' => ' 23', 'model' => ' HR-V II (GJ)'],
            ['brand_id' => ' 23', 'model' => ' Insight'],
            ['brand_id' => ' 23', 'model' => ' Insight II (ZE2)'],
            ['brand_id' => ' 23', 'model' => ' Jazz'],
            ['brand_id' => ' 23', 'model' => ' Legend'],
            ['brand_id' => ' 23', 'model' => ' Odyssey'],
            ['brand_id' => ' 23', 'model' => ' Pilot'],
            ['brand_id' => ' 23', 'model' => ' Prelude'],
            ['brand_id' => ' 23', 'model' => ' Ridgeline'],
            ['brand_id' => ' 23', 'model' => ' S2000'],
            ['brand_id' => ' 23', 'model' => ' Shuttle'],
            ['brand_id' => ' 23', 'model' => ' Stream'],
            ['brand_id' => ' 24', 'model' => ' H2'],
            ['brand_id' => ' 24', 'model' => ' H3'],
            ['brand_id' => ' 2525', 'model' => ' Accent'],
            ['brand_id' => ' 25', 'model' => ' Atos Prime'],
            ['brand_id' => ' 25', 'model' => ' Azera'],
            ['brand_id' => ' 25', 'model' => ' Centennial'],
            ['brand_id' => ' 25', 'model' => ' Creta'],
            ['brand_id' => ' 25', 'model' => ' Elantra'],
            ['brand_id' => ' 25', 'model' => ' Entourage'],
            ['brand_id' => ' 25', 'model' => ' Eon'],
            ['brand_id' => ' 25', 'model' => ' Equus'],
            ['brand_id' => ' 25', 'model' => ' Galloper'],
            ['brand_id' => ' 25', 'model' => ' Genesis'],
            ['brand_id' => ' 25', 'model' => ' Genesis Coupe'],
            ['brand_id' => ' 25', 'model' => ' Getz'],
            ['brand_id' => ' 25', 'model' => ' Grandeur'],
            ['brand_id' => ' 25', 'model' => ' H1'],
            ['brand_id' => ' 25', 'model' => ' i10'],
            ['brand_id' => ' 25', 'model' => ' i20'],
            ['brand_id' => ' 25', 'model' => ' i30'],
            ['brand_id' => ' 25', 'model' => ' i40'],
            ['brand_id' => ' 25', 'model' => ' ix20'],
            ['brand_id' => ' 25', 'model' => ' ix35'],
            ['brand_id' => ' 25', 'model' => ' Matrix'],
            ['brand_id' => ' 25', 'model' => ' Porter'],
            ['brand_id' => ' 25', 'model' => ' Santa Fe'],
            ['brand_id' => ' 25', 'model' => ' Solaris'],
            ['brand_id' => ' 25', 'model' => ' Sonata'],
            ['brand_id' => ' 25', 'model' => ' Terracan'],
            ['brand_id' => ' 25', 'model' => ' Trajet'],
            ['brand_id' => ' 25', 'model' => ' Tucson'],
            ['brand_id' => ' 25', 'model' => ' Veloster'],
            ['brand_id' => ' 25', 'model' => ' Veracruz'],
            ['brand_id' => ' 25', 'model' => ' Verna'],
            ['brand_id' => ' 25', 'model' => ' Xcent'],
            ['brand_id' => ' 25', 'model' => ' XG'],
            ['brand_id' => ' 26', 'model' => ' EX'],
            ['brand_id' => ' 26', 'model' => ' FX'],
            ['brand_id' => ' 26', 'model' => ' G'],
            ['brand_id' => ' 26', 'model' => ' I35'],
            ['brand_id' => ' 26', 'model' => ' JX'],
            ['brand_id' => ' 26', 'model' => ' M'],
            ['brand_id' => ' 26', 'model' => ' Q30'],
            ['brand_id' => ' 26', 'model' => ' Q40'],
            ['brand_id' => ' 26', 'model' => ' Q45'],
            ['brand_id' => ' 26', 'model' => ' Q50'],
            ['brand_id' => ' 26', 'model' => ' Q60'],
            ['brand_id' => ' 26', 'model' => ' Q70'],
            ['brand_id' => ' 26', 'model' => ' QX30'],
            ['brand_id' => ' 26', 'model' => ' QX4'],
            ['brand_id' => ' 26', 'model' => ' QX50'],
            ['brand_id' => ' 26', 'model' => ' QX56'],
            ['brand_id' => ' 26', 'model' => ' QX60'],
            ['brand_id' => ' 26', 'model' => ' QX70'],
            ['brand_id' => ' 26', 'model' => ' QX80'],
            ['brand_id' => ' 27', 'model' => ' Ascender'],
            ['brand_id' => ' 27', 'model' => ' Axiom'],
            ['brand_id' => ' 27', 'model' => ' D-Max'],
            ['brand_id' => ' 27', 'model' => ' D-Max Rodeo'],
            ['brand_id' => ' 27', 'model' => ' I280'],
            ['brand_id' => ' 27', 'model' => ' I290'],
            ['brand_id' => ' 27', 'model' => ' I350'],
            ['brand_id' => ' 27', 'model' => ' I370'],
            ['brand_id' => ' 27', 'model' => ' Rodeo'],
            ['brand_id' => ' 27', 'model' => ' Trooper'],
            ['brand_id' => ' 27', 'model' => ' VehiCross'],
            ['brand_id' => ' 28', 'model' => ' F-Pace'],
            ['brand_id' => ' 28', 'model' => ' F-Type'],
            ['brand_id' => ' 28', 'model' => ' S-Type'],
            ['brand_id' => ' 28', 'model' => ' X-Type'],
            ['brand_id' => ' 28', 'model' => ' XE'],
            ['brand_id' => ' 28', 'model' => ' XF'],
            ['brand_id' => ' 28', 'model' => ' XFR'],
            ['brand_id' => ' 28', 'model' => ' XJ'],
            ['brand_id' => ' 28', 'model' => ' XK/XKR'],
            ['brand_id' => ' 29', 'model' => ' Cherokee'],
            ['brand_id' => ' 29', 'model' => ' Commander'],
            ['brand_id' => ' 29', 'model' => ' Compass'],
            ['brand_id' => ' 29', 'model' => ' Grand Cherokee'],
            ['brand_id' => ' 29', 'model' => ' Liberty'],
            ['brand_id' => ' 29', 'model' => ' Renegade'],
            ['brand_id' => ' 29', 'model' => ' Wrangler'],
            ['brand_id' => ' 30', 'model' => ' Carens'],
            ['brand_id' => ' 30', 'model' => ' Carnival'],
            ['brand_id' => ' 30', 'model' => ' Ceed'],
            ['brand_id' => ' 30', 'model' => ' Cerato'],
            ['brand_id' => ' 30', 'model' => ' Clarus'],
            ['brand_id' => ' 30', 'model' => ' Forte'],
            ['brand_id' => ' 30', 'model' => ' Magentis'],
            ['brand_id' => ' 30', 'model' => ' Mohave'],
            ['brand_id' => ' 30', 'model' => ' Opirus'],
            ['brand_id' => ' 30', 'model' => ' Optima'],
            ['brand_id' => ' 30', 'model' => ' Picanto'],
            ['brand_id' => ' 30', 'model' => ' Quoris'],
            ['brand_id' => ' 30', 'model' => ' Ray'],
            ['brand_id' => ' 30', 'model' => ' Rio'],
            ['brand_id' => ' 30', 'model' => ' Shuma'],
            ['brand_id' => ' 30', 'model' => ' Sorento'],
            ['brand_id' => ' 30', 'model' => ' Soul'],
            ['brand_id' => ' 30', 'model' => ' Spectra'],
            ['brand_id' => ' 30', 'model' => ' Sportage'],
            ['brand_id' => ' 30', 'model' => ' Venga'],
            ['brand_id' => ' 31', 'model' => ' Aventador'],
            ['brand_id' => ' 31', 'model' => ' Diablo'],
            ['brand_id' => ' 31', 'model' => ' Gallardo'],
            ['brand_id' => ' 31', 'model' => ' Huracan'],
            ['brand_id' => ' 31', 'model' => ' Murcielago'],
            ['brand_id' => ' 31', 'model' => ' Reventon'],
            ['brand_id' => ' 32', 'model' => ' Delta'],
            ['brand_id' => ' 32', 'model' => ' Lybra'],
            ['brand_id' => ' 32', 'model' => ' Musa'],
            ['brand_id' => ' 32', 'model' => ' Phedra'],
            ['brand_id' => ' 32', 'model' => ' Thema'],
            ['brand_id' => ' 32', 'model' => ' Thesis'],
            ['brand_id' => ' 32', 'model' => ' Ypsilon'],
            ['brand_id' => ' 33', 'model' => ' Defender'],
            ['brand_id' => ' 33', 'model' => ' Discovery'],
            ['brand_id' => ' 33', 'model' => ' Discovery Sport'],
            ['brand_id' => ' 33', 'model' => ' Evoque'],
            ['brand_id' => ' 33', 'model' => ' Freelander'],
            ['brand_id' => ' 33', 'model' => ' Range Rover'],
            ['brand_id' => ' 33', 'model' => ' Range Rover Sport'],
            ['brand_id' => ' 34', 'model' => ' CT'],
            ['brand_id' => ' 34', 'model' => ' ES'],
            ['brand_id' => ' 34', 'model' => ' GS'],
            ['brand_id' => ' 34', 'model' => ' GX'],
            ['brand_id' => ' 34', 'model' => ' HS'],
            ['brand_id' => ' 34', 'model' => ' IS'],
            ['brand_id' => ' 34', 'model' => ' LFA'],
            ['brand_id' => ' 34', 'model' => ' LS'],
            ['brand_id' => ' 34', 'model' => ' LX'],
            ['brand_id' => ' 34', 'model' => ' NX'],
            ['brand_id' => ' 34', 'model' => ' RC'],
            ['brand_id' => ' 34', 'model' => ' RX'],
            ['brand_id' => ' 34', 'model' => ' SC'],
            ['brand_id' => ' 35', 'model' => ' Breez'],
            ['brand_id' => ' 35', 'model' => ' Cebrium'],
            ['brand_id' => ' 35', 'model' => ' Smily'],
            ['brand_id' => ' 35', 'model' => ' Solano'],
            ['brand_id' => ' 35', 'model' => ' X60'],
            ['brand_id' => ' 36', 'model' => ' Aviator'],
            ['brand_id' => ' 36', 'model' => ' Mark LT'],
            ['brand_id' => ' 36', 'model' => ' MKS'],
            ['brand_id' => ' 36', 'model' => ' MKT'],
            ['brand_id' => ' 36', 'model' => ' MKX'],
            ['brand_id' => ' 36', 'model' => ' MKZ'],
            ['brand_id' => ' 36', 'model' => ' Navigator'],
            ['brand_id' => ' 36', 'model' => ' Town Car'],
            ['brand_id' => ' 36', 'model' => ' Zephyr'],
            ['brand_id' => ' 37', 'model' => ' Elise'],
            ['brand_id' => ' 37', 'model' => ' Europa S'],
            ['brand_id' => ' 37', 'model' => ' Evora'],
            ['brand_id' => ' 37', 'model' => ' Exige'],
            ['brand_id' => ' 38', 'model' => ' B1'],
            ['brand_id' => ' 38', 'model' => ' B2'],
            ['brand_id' => ' 39', 'model' => ' 3200 GT'],
            ['brand_id' => ' 39', 'model' => ' Ghibli'],
            ['brand_id' => ' 39', 'model' => ' Gran Cabrio'],
            ['brand_id' => ' 39', 'model' => ' Gran Turismo '],
            ['brand_id' => ' 39', 'model' => ' Gran Turismo S'],
            ['brand_id' => ' 39', 'model' => ' Levante'],
            ['brand_id' => ' 39', 'model' => ' Quattroporte'],
            ['brand_id' => ' 39', 'model' => ' Quattroporte S'],
            ['brand_id' => ' 40', 'model' => ' 57'],
            ['brand_id' => ' 40', 'model' => ' 57 S'],
            ['brand_id' => ' 40', 'model' => ' 62'],
            ['brand_id' => ' 40', 'model' => ' 62 S'],
            ['brand_id' => ' 40', 'model' => ' Landaulet'],
            ['brand_id' => ' 41', 'model' => ' 2'],
            ['brand_id' => ' 41', 'model' => ' 3'],
            ['brand_id' => ' 41', 'model' => ' 323'],
            ['brand_id' => ' 41', 'model' => ' 5'],
            ['brand_id' => ' 41', 'model' => ' 6'],
            ['brand_id' => ' 41', 'model' => ' 626'],
            ['brand_id' => ' 41', 'model' => ' B-Series'],
            ['brand_id' => ' 41', 'model' => ' BT-50'],
            ['brand_id' => ' 41', 'model' => ' CX-3'],
            ['brand_id' => ' 41', 'model' => ' CX-5'],
            ['brand_id' => ' 41', 'model' => ' CX-7'],
            ['brand_id' => ' 41', 'model' => ' CX-9'],
            ['brand_id' => ' 41', 'model' => ' MPV'],
            ['brand_id' => ' 41', 'model' => ' MX-5'],
            ['brand_id' => ' 41', 'model' => ' Premacy'],
            ['brand_id' => ' 41', 'model' => ' RX-7'],
            ['brand_id' => ' 41', 'model' => ' RX-8'],
            ['brand_id' => ' 41', 'model' => ' Tribute'],
            ['brand_id' => ' 42', 'model' => ' 540C'],
            ['brand_id' => ' 42', 'model' => ' 570S'],
            ['brand_id' => ' 42', 'model' => ' 650S'],
            ['brand_id' => ' 42', 'model' => ' 675LT'],
            ['brand_id' => ' 42', 'model' => ' MP4-12C'],
            ['brand_id' => ' 42', 'model' => ' P1'],
            ['brand_id' => ' 43', 'model' => ' A-class'],
            ['brand_id' => ' 43', 'model' => ' AMG GT'],
            ['brand_id' => ' 43', 'model' => ' B-class'],
            ['brand_id' => ' 43', 'model' => ' B-Klass'],
            ['brand_id' => ' 43', 'model' => ' C-class'],
            ['brand_id' => ' 43', 'model' => ' C-class Sport Coupe'],
            ['brand_id' => ' 43', 'model' => ' CL-class'],
            ['brand_id' => ' 43', 'model' => ' CLA-Class'],
            ['brand_id' => ' 43', 'model' => ' CLC-class '],
            ['brand_id' => ' 43', 'model' => ' CLK-class'],
            ['brand_id' => ' 43', 'model' => ' CLS-class'],
            ['brand_id' => ' 43', 'model' => ' E-class'],
            ['brand_id' => ' 43', 'model' => ' G-class'],
            ['brand_id' => ' 43', 'model' => ' GL-class'],
            ['brand_id' => ' 43', 'model' => ' GLA-class'],
            ['brand_id' => ' 43', 'model' => ' GLC-Class'],
            ['brand_id' => ' 43', 'model' => ' GLE Coupe'],
            ['brand_id' => ' 43', 'model' => ' GLE-Class'],
            ['brand_id' => ' 43', 'model' => ' GLK-class'],
            ['brand_id' => ' 43', 'model' => ' M-class'],
            ['brand_id' => ' 43', 'model' => ' R-class'],
            ['brand_id' => ' 43', 'model' => ' S-class'],
            ['brand_id' => ' 43', 'model' => ' SL-class'],
            ['brand_id' => ' 43', 'model' => ' SLK-class'],
            ['brand_id' => ' 43', 'model' => ' SLR-class'],
            ['brand_id' => ' 43', 'model' => ' SLS AMG'],
            ['brand_id' => ' 43', 'model' => ' Sprinter'],
            ['brand_id' => ' 43', 'model' => ' Vaneo'],
            ['brand_id' => ' 43', 'model' => ' Viano'],
            ['brand_id' => ' 43', 'model' => ' Vito'],
            ['brand_id' => ' 44', 'model' => ' Grand Marquis'],
            ['brand_id' => ' 44', 'model' => ' Mariner'],
            ['brand_id' => ' 44', 'model' => ' Milan'],
            ['brand_id' => ' 44', 'model' => ' Montego'],
            ['brand_id' => ' 44', 'model' => ' Monterey'],
            ['brand_id' => ' 44', 'model' => ' Mountaineer'],
            ['brand_id' => ' 44', 'model' => ' Sable'],
            ['brand_id' => ' 45', 'model' => ' TF'],
            ['brand_id' => ' 45', 'model' => ' XPower SV'],
            ['brand_id' => ' 45', 'model' => ' ZR'],
            ['brand_id' => ' 45', 'model' => ' ZS'],
            ['brand_id' => ' 45', 'model' => ' ZT'],
            ['brand_id' => ' 45', 'model' => ' ZT-T'],
            ['brand_id' => ' 46', 'model' => ' Clubman'],
            ['brand_id' => ' 46', 'model' => ' Clubman S'],
            ['brand_id' => ' 46', 'model' => ' Cooper'],
            ['brand_id' => ' 46', 'model' => ' Cooper Cabrio'],
            ['brand_id' => ' 46', 'model' => ' Cooper Countryman'],
            ['brand_id' => ' 46', 'model' => ' Cooper S'],
            ['brand_id' => ' 46', 'model' => ' Cooper S Cabrio'],
            ['brand_id' => ' 46', 'model' => ' Cooper S Countryman All4'],
            ['brand_id' => ' 46', 'model' => ' JCW'],
            ['brand_id' => ' 46', 'model' => ' One'],
            ['brand_id' => ' 47', 'model' => ' 3000 GT'],
            ['brand_id' => ' 47', 'model' => ' ASX'],
            ['brand_id' => ' 47', 'model' => ' Carisma'],
            ['brand_id' => ' 47', 'model' => ' Colt'],
            ['brand_id' => ' 47', 'model' => ' Dignity'],
            ['brand_id' => ' 47', 'model' => ' Eclipse'],
            ['brand_id' => ' 47', 'model' => ' Endeavor'],
            ['brand_id' => ' 47', 'model' => ' Galant'],
            ['brand_id' => ' 47', 'model' => ' Grandis'],
            ['brand_id' => ' 47', 'model' => ' i-MiEV'],
            ['brand_id' => ' 47', 'model' => ' L200'],
            ['brand_id' => ' 47', 'model' => ' Lancer'],
            ['brand_id' => ' 47', 'model' => ' Lancer Evo'],
            ['brand_id' => ' 47', 'model' => ' Mirage'],
            ['brand_id' => ' 47', 'model' => ' Outlander'],
            ['brand_id' => ' 47', 'model' => ' Outlander XL'],
            ['brand_id' => ' 47', 'model' => ' Pajero'],
            ['brand_id' => ' 47', 'model' => ' Pajero Pinin'],
            ['brand_id' => ' 47', 'model' => ' Pajero Sport'],
            ['brand_id' => ' 47', 'model' => ' Raider'],
            ['brand_id' => ' 47', 'model' => ' Space Gear'],
            ['brand_id' => ' 47', 'model' => ' Space Runner'],
            ['brand_id' => ' 47', 'model' => ' Space Star'],
            ['brand_id' => ' 48', 'model' => ' 350Z'],
            ['brand_id' => ' 48', 'model' => ' 370Z'],
            ['brand_id' => ' 48', 'model' => ' Almera'],
            ['brand_id' => ' 48', 'model' => ' Almera Classic'],
            ['brand_id' => ' 48', 'model' => ' Almera Tino'],
            ['brand_id' => ' 48', 'model' => ' Altima'],
            ['brand_id' => ' 48', 'model' => ' Armada'],
            ['brand_id' => ' 48', 'model' => ' GT-R'],
            ['brand_id' => ' 48', 'model' => ' Juke'],
            ['brand_id' => ' 48', 'model' => ' Leaf'],
            ['brand_id' => ' 48', 'model' => ' Maxima'],
            ['brand_id' => ' 48', 'model' => ' Micra'],
            ['brand_id' => ' 48', 'model' => ' Murano'],
            ['brand_id' => ' 48', 'model' => ' Navara'],
            ['brand_id' => ' 48', 'model' => ' Note'],
            ['brand_id' => ' 48', 'model' => ' NP300'],
            ['brand_id' => ' 48', 'model' => ' Pathfinder'],
            ['brand_id' => ' 48', 'model' => ' Patrol'],
            ['brand_id' => ' 48', 'model' => ' Primera'],
            ['brand_id' => ' 48', 'model' => ' Qashqai'],
            ['brand_id' => ' 48', 'model' => ' Qashqai+2'],
            ['brand_id' => ' 48', 'model' => ' Quest'],
            ['brand_id' => ' 48', 'model' => ' Sentra'],
            ['brand_id' => ' 48', 'model' => ' Skyline'],
            ['brand_id' => ' 48', 'model' => ' Teana'],
            ['brand_id' => ' 48', 'model' => ' Terrano'],
            ['brand_id' => ' 48', 'model' => ' Tiida'],
            ['brand_id' => ' 48', 'model' => ' Titan'],
            ['brand_id' => ' 48', 'model' => ' X-Trail'],
            ['brand_id' => ' 48', 'model' => ' XTerra'],
            ['brand_id' => ' 48', 'model' => ' Z'],
            ['brand_id' => ' 49', 'model' => ' Adam'],
            ['brand_id' => ' 49', 'model' => ' Agila'],
            ['brand_id' => ' 49', 'model' => ' Antara'],
            ['brand_id' => ' 49', 'model' => ' Astra'],
            ['brand_id' => ' 49', 'model' => ' Astra GTS'],
            ['brand_id' => ' 49', 'model' => ' Cascada'],
            ['brand_id' => ' 49', 'model' => ' Combo'],
            ['brand_id' => ' 49', 'model' => ' Corsa'],
            ['brand_id' => ' 49', 'model' => ' Frontera'],
            ['brand_id' => ' 49', 'model' => ' Insignia'],
            ['brand_id' => ' 49', 'model' => ' Karl'],
            ['brand_id' => ' 49', 'model' => ' Meriva'],
            ['brand_id' => ' 49', 'model' => ' Mokka'],
            ['brand_id' => ' 49', 'model' => ' Omega'],
            ['brand_id' => ' 49', 'model' => ' Signum'],
            ['brand_id' => ' 49', 'model' => ' Speedster'],
            ['brand_id' => ' 49', 'model' => ' Tigra'],
            ['brand_id' => ' 49', 'model' => ' Vectra'],
            ['brand_id' => ' 49', 'model' => ' Vivaro'],
            ['brand_id' => ' 49', 'model' => ' Zafira'],
            ['brand_id' => ' 49', 'model' => ' Zafira Tourer'],
            ['brand_id' => ' 50', 'model' => ' 1007'],
            ['brand_id' => ' 50', 'model' => ' 107'],
            ['brand_id' => ' 50', 'model' => ' 108'],
            ['brand_id' => ' 50', 'model' => ' 2008'],
            ['brand_id' => ' 50', 'model' => ' 206'],
            ['brand_id' => ' 50', 'model' => ' 207'],
            ['brand_id' => ' 50', 'model' => ' 208'],
            ['brand_id' => ' 50', 'model' => ' 3008'],
            ['brand_id' => ' 50', 'model' => ' 301'],
            ['brand_id' => ' 50', 'model' => ' 307'],
            ['brand_id' => ' 50', 'model' => ' 308'],
            ['brand_id' => ' 50', 'model' => ' 4007'],
            ['brand_id' => ' 50', 'model' => ' 4008'],
            ['brand_id' => ' 50', 'model' => ' 406'],
            ['brand_id' => ' 50', 'model' => ' 407'],
            ['brand_id' => ' 50', 'model' => ' 408'],
            ['brand_id' => ' 50', 'model' => ' 5008'],
            ['brand_id' => ' 50', 'model' => ' 508'],
            ['brand_id' => ' 50', 'model' => ' 607'],
            ['brand_id' => ' 50', 'model' => ' 807'],
            ['brand_id' => ' 50', 'model' => ' Boxer'],
            ['brand_id' => ' 50', 'model' => ' Partner'],
            ['brand_id' => ' 50', 'model' => ' RCZ Sport'],
            ['brand_id' => ' 51', 'model' => ' Aztec'],
            ['brand_id' => ' 51', 'model' => ' Bonneville'],
            ['brand_id' => ' 51', 'model' => ' Firebird'],
            ['brand_id' => ' 51', 'model' => ' G5'],
            ['brand_id' => ' 51', 'model' => ' G6'],
            ['brand_id' => ' 51', 'model' => ' G8'],
            ['brand_id' => ' 51', 'model' => ' Grand AM'],
            ['brand_id' => ' 51', 'model' => ' Grand Prix'],
            ['brand_id' => ' 51', 'model' => ' GTO'],
            ['brand_id' => ' 51', 'model' => ' Montana'],
            ['brand_id' => ' 51', 'model' => ' Solstice'],
            ['brand_id' => ' 51', 'model' => ' Sunfire'],
            ['brand_id' => ' 51', 'model' => ' Torrent'],
            ['brand_id' => ' 51', 'model' => ' Vibe'],
            ['brand_id' => ' 52', 'model' => ' 911'],
            ['brand_id' => ' 52', 'model' => ' Boxster'],
            ['brand_id' => ' 52', 'model' => ' Cayenne'],
            ['brand_id' => ' 52', 'model' => ' Cayman'],
            ['brand_id' => ' 52', 'model' => ' Macan'],
            ['brand_id' => ' 52', 'model' => ' Panamera'],
            ['brand_id' => ' 53', 'model' => ' Avantime'],
            ['brand_id' => ' 53', 'model' => ' Captur'],
            ['brand_id' => ' 53', 'model' => ' Clio'],
            ['brand_id' => ' 53', 'model' => ' Duster'],
            ['brand_id' => ' 53', 'model' => ' Duster Oroch'],
            ['brand_id' => ' 53', 'model' => ' Espace'],
            ['brand_id' => ' 53', 'model' => ' Fluence'],
            ['brand_id' => ' 53', 'model' => ' Kadjar'],
            ['brand_id' => ' 53', 'model' => ' Kangoo'],
            ['brand_id' => ' 53', 'model' => ' Kaptur'],
            ['brand_id' => ' 53', 'model' => ' Koleos'],
            ['brand_id' => ' 53', 'model' => ' Laguna'],
            ['brand_id' => ' 53', 'model' => ' Latitude'],
            ['brand_id' => ' 53', 'model' => ' Logan'],
            ['brand_id' => ' 53', 'model' => ' Master'],
            ['brand_id' => ' 53', 'model' => ' Megane'],
            ['brand_id' => ' 53', 'model' => ' Modus'],
            ['brand_id' => ' 53', 'model' => ' Sandero'],
            ['brand_id' => ' 53', 'model' => ' Sandero Stepway'],
            ['brand_id' => ' 53', 'model' => ' Scenic'],
            ['brand_id' => ' 53', 'model' => ' Symbol'],
            ['brand_id' => ' 53', 'model' => ' Talisman'],
            ['brand_id' => ' 53', 'model' => ' Trafic'],
            ['brand_id' => ' 53', 'model' => ' Twingo'],
            ['brand_id' => ' 53', 'model' => ' Twizy'],
            ['brand_id' => ' 53', 'model' => ' Vel Satis'],
            ['brand_id' => ' 53', 'model' => ' Wind'],
            ['brand_id' => ' 53', 'model' => ' Zoe'],
            ['brand_id' => ' 54', 'model' => ' Ghost'],
            ['brand_id' => ' 54', 'model' => ' Phantom'],
            ['brand_id' => ' 55', 'model' => ' 25'],
            ['brand_id' => ' 55', 'model' => ' 400'],
            ['brand_id' => ' 55', 'model' => ' 45'],
            ['brand_id' => ' 55', 'model' => ' 600'],
            ['brand_id' => ' 55', 'model' => ' 75'],
            ['brand_id' => ' 55', 'model' => ' Streetwise'],
            ['brand_id' => ' 56', 'model' => ' 9-2x'],
            ['brand_id' => ' 56', 'model' => ' 43168'],
            ['brand_id' => ' 56', 'model' => ' 9-4x'],
            ['brand_id' => ' 56', 'model' => ' 43229'],
            ['brand_id' => ' 56', 'model' => ' 9-7x'],
            ['brand_id' => ' 57', 'model' => ' Aura'],
            ['brand_id' => ' 57', 'model' => ' Ion'],
            ['brand_id' => ' 57', 'model' => ' LW'],
            ['brand_id' => ' 57', 'model' => ' Outlook'],
            ['brand_id' => ' 57', 'model' => ' Sky'],
            ['brand_id' => ' 57', 'model' => ' Vue'],
            ['brand_id' => ' 58', 'model' => ' tC'],
            ['brand_id' => ' 58', 'model' => ' xA'],
            ['brand_id' => ' 58', 'model' => ' xB'],
            ['brand_id' => ' 58', 'model' => ' xD'],
            ['brand_id' => ' 59', 'model' => ' Alhambra'],
            ['brand_id' => ' 59', 'model' => ' Altea'],
            ['brand_id' => ' 59', 'model' => ' Altea Freetrack'],
            ['brand_id' => ' 59', 'model' => ' Altea XL'],
            ['brand_id' => ' 59', 'model' => ' Arosa'],
            ['brand_id' => ' 59', 'model' => ' Cordoba'],
            ['brand_id' => ' 59', 'model' => ' Exeo'],
            ['brand_id' => ' 59', 'model' => ' Ibiza'],
            ['brand_id' => ' 59', 'model' => ' Leon'],
            ['brand_id' => ' 59', 'model' => ' Mii'],
            ['brand_id' => ' 59', 'model' => ' Toledo'],
            ['brand_id' => ' 60', 'model' => ' Citigo'],
            ['brand_id' => ' 60', 'model' => ' Fabia'],
            ['brand_id' => ' 60', 'model' => ' Felicia'],
            ['brand_id' => ' 60', 'model' => ' Octavia'],
            ['brand_id' => ' 60', 'model' => ' Octavia Scout'],
            ['brand_id' => ' 60', 'model' => ' Octavia Tour'],
            ['brand_id' => ' 60', 'model' => ' Praktik'],
            ['brand_id' => ' 60', 'model' => ' Rapid'],
            ['brand_id' => ' 60', 'model' => ' Rapid Spaceback (NH1)'],
            ['brand_id' => ' 60', 'model' => ' Roomster'],
            ['brand_id' => ' 60', 'model' => ' Superb'],
            ['brand_id' => ' 60', 'model' => ' Yeti'],
            ['brand_id' => ' 61', 'model' => ' Forfour'],
            ['brand_id' => ' 61', 'model' => ' Fortwo'],
            ['brand_id' => ' 61', 'model' => ' Roadster'],
            ['brand_id' => ' 62', 'model' => ' Actyon'],
            ['brand_id' => ' 62', 'model' => ' Actyon Sports'],
            ['brand_id' => ' 62', 'model' => ' Chairman'],
            ['brand_id' => ' 62', 'model' => ' Korando'],
            ['brand_id' => ' 62', 'model' => ' Kyron'],
            ['brand_id' => ' 62', 'model' => ' Musso'],
            ['brand_id' => ' 62', 'model' => ' Musso Sport'],
            ['brand_id' => ' 62', 'model' => ' Rexton'],
            ['brand_id' => ' 62', 'model' => ' Rodius'],
            ['brand_id' => ' 62', 'model' => ' Stavic'],
            ['brand_id' => ' 62', 'model' => ' Tivoli'],
            ['brand_id' => ' 63', 'model' => ' Baja'],
            ['brand_id' => ' 63', 'model' => ' Exiga'],
            ['brand_id' => ' 63', 'model' => ' Forester'],
            ['brand_id' => ' 63', 'model' => ' Impreza'],
            ['brand_id' => ' 63', 'model' => ' Justy'],
            ['brand_id' => ' 63', 'model' => ' Legacy'],
            ['brand_id' => ' 63', 'model' => ' Levorg'],
            ['brand_id' => ' 63', 'model' => ' Outback'],
            ['brand_id' => ' 63', 'model' => ' Traviq'],
            ['brand_id' => ' 63', 'model' => ' Tribeca'],
            ['brand_id' => ' 63', 'model' => ' WRX'],
            ['brand_id' => ' 63', 'model' => ' XV'],
            ['brand_id' => ' 64', 'model' => ' Alto'],
            ['brand_id' => ' 64', 'model' => ' Baleno'],
            ['brand_id' => ' 64', 'model' => ' Celerio'],
            ['brand_id' => ' 64', 'model' => ' Ciaz'],
            ['brand_id' => ' 64', 'model' => ' Grand Vitara'],
            ['brand_id' => ' 64', 'model' => ' Grand Vitara XL7'],
            ['brand_id' => ' 64', 'model' => ' Ignis'],
            ['brand_id' => ' 64', 'model' => ' Jimny'],
            ['brand_id' => ' 64', 'model' => ' Kizashi'],
            ['brand_id' => ' 64', 'model' => ' Liana'],
            ['brand_id' => ' 64', 'model' => ' Splash'],
            ['brand_id' => ' 64', 'model' => ' Swift'],
            ['brand_id' => ' 64', 'model' => ' SX4'],
            ['brand_id' => ' 64', 'model' => ' Wagon R'],
            ['brand_id' => ' 64', 'model' => ' Wagon R+'],
            ['brand_id' => ' 65', 'model' => ' Model S'],
            ['brand_id' => ' 65', 'model' => ' Model X'],
            ['brand_id' => ' 66', 'model' => ' 4Runner'],
            ['brand_id' => ' 66', 'model' => ' Alphard'],
            ['brand_id' => ' 66', 'model' => ' Auris'],
            ['brand_id' => ' 66', 'model' => ' Avalon'],
            ['brand_id' => ' 66', 'model' => ' Avensis'],
            ['brand_id' => ' 66', 'model' => ' Avensis Verso'],
            ['brand_id' => ' 66', 'model' => ' Aygo'],
            ['brand_id' => ' 66', 'model' => ' Camry'],
            ['brand_id' => ' 66', 'model' => ' Celica'],
            ['brand_id' => ' 66', 'model' => ' Corolla'],
            ['brand_id' => ' 66', 'model' => ' Corolla Verso'],
            ['brand_id' => ' 66', 'model' => ' FJ Cruiser'],
            ['brand_id' => ' 66', 'model' => ' Fortuner'],
            ['brand_id' => ' 66', 'model' => ' GT 86'],
            ['brand_id' => ' 66', 'model' => ' Hiace'],
            ['brand_id' => ' 66', 'model' => ' Highlander'],
            ['brand_id' => ' 66', 'model' => ' Hilux'],
            ['brand_id' => ' 66', 'model' => ' iQ'],
            ['brand_id' => ' 66', 'model' => ' ist'],
            ['brand_id' => ' 66', 'model' => ' Land Cruiser'],
            ['brand_id' => ' 66', 'model' => ' Land Cruiser Prado'],
            ['brand_id' => ' 66', 'model' => ' Mark II'],
            ['brand_id' => ' 66', 'model' => ' Mirai'],
            ['brand_id' => ' 66', 'model' => ' MR2'],
            ['brand_id' => ' 66', 'model' => ' Picnic'],
            ['brand_id' => ' 66', 'model' => ' Previa'],
            ['brand_id' => ' 66', 'model' => ' Prius'],
            ['brand_id' => ' 66', 'model' => ' RAV4'],
            ['brand_id' => ' 66', 'model' => ' Sequoia'],
            ['brand_id' => ' 66', 'model' => ' Sienna'],
            ['brand_id' => ' 66', 'model' => ' Tacoma'],
            ['brand_id' => ' 66', 'model' => ' Tundra'],
            ['brand_id' => ' 66', 'model' => ' Venza'],
            ['brand_id' => ' 66', 'model' => ' Verso'],
            ['brand_id' => ' 66', 'model' => ' Vitz'],
            ['brand_id' => ' 66', 'model' => ' Yaris'],
            ['brand_id' => ' 66', 'model' => ' Yaris Verso'],
            ['brand_id' => ' 67', 'model' => ' Amarok'],
            ['brand_id' => ' 67', 'model' => ' Beetle'],
            ['brand_id' => ' 67', 'model' => ' Bora'],
            ['brand_id' => ' 67', 'model' => ' Caddy'],
            ['brand_id' => ' 67', 'model' => ' Crafter'],
            ['brand_id' => ' 67', 'model' => ' CrossGolf'],
            ['brand_id' => ' 67', 'model' => ' CrossPolo'],
            ['brand_id' => ' 67', 'model' => ' CrossTouran'],
            ['brand_id' => ' 67', 'model' => ' Eos'],
            ['brand_id' => ' 67', 'model' => ' Fox'],
            ['brand_id' => ' 67', 'model' => ' Golf'],
            ['brand_id' => ' 67', 'model' => ' Jetta'],
            ['brand_id' => ' 67', 'model' => ' Lupo'],
            ['brand_id' => ' 67', 'model' => ' Multivan'],
            ['brand_id' => ' 67', 'model' => ' New Beetle'],
            ['brand_id' => ' 67', 'model' => ' Passat'],
            ['brand_id' => ' 67', 'model' => ' Passat CC'],
            ['brand_id' => ' 67', 'model' => ' Phaeton'],
            ['brand_id' => ' 67', 'model' => ' Pointer'],
            ['brand_id' => ' 67', 'model' => ' Polo'],
            ['brand_id' => ' 67', 'model' => ' Routan'],
            ['brand_id' => ' 67', 'model' => ' Scirocco'],
            ['brand_id' => ' 67', 'model' => ' Sharan'],
            ['brand_id' => ' 67', 'model' => ' Tiguan'],
            ['brand_id' => ' 67', 'model' => ' Touareg'],
            ['brand_id' => ' 67', 'model' => ' Touran'],
            ['brand_id' => ' 67', 'model' => ' Transporter'],
            ['brand_id' => ' 67', 'model' => ' Up'],
            ['brand_id' => ' 68', 'model' => ' C30'],
            ['brand_id' => ' 68', 'model' => ' C70'],
            ['brand_id' => ' 68', 'model' => ' C70 Convertible'],
            ['brand_id' => ' 68', 'model' => ' C70 Coupe'],
            ['brand_id' => ' 68', 'model' => ' S40'],
            ['brand_id' => ' 68', 'model' => ' S60'],
            ['brand_id' => ' 68', 'model' => ' S70'],
            ['brand_id' => ' 68', 'model' => ' S80'],
            ['brand_id' => ' 68', 'model' => ' S90'],
            ['brand_id' => ' 68', 'model' => ' V40'],
            ['brand_id' => ' 68', 'model' => ' V40 Cross Country'],
            ['brand_id' => ' 68', 'model' => ' V50'],
            ['brand_id' => ' 68', 'model' => ' V60'],
            ['brand_id' => ' 68', 'model' => ' V70'],
            ['brand_id' => ' 68', 'model' => ' V90'],
            ['brand_id' => ' 68', 'model' => ' XC60'],
            ['brand_id' => ' 68', 'model' => ' XC70'],
            ['brand_id' => ' 68', 'model' => ' XC90'],
            ['brand_id' => ' 69', 'model' => ' 2101-2107'],
            ['brand_id' => ' 69', 'model' => ' 2108, 2109, 21099'],
            ['brand_id' => ' 69', 'model' => ' 2110, 2111, 2112'],
            ['brand_id' => ' 69', 'model' => ' 2113, 2114, 2115'],
            ['brand_id' => ' 69', 'model' => ' Granta'],
            ['brand_id' => ' 69', 'model' => ' Largus'],
            ['brand_id' => ' 69', 'model' => ' XRay'],
            ['brand_id' => ' 69', 'model' => ' Веста'],
            ['brand_id' => ' 69', 'model' => ' Калина'],
            ['brand_id' => ' 69', 'model' => ' Нива 4X4'],
            ['brand_id' => ' 69', 'model' => ' Ока'],
            ['brand_id' => ' 69', 'model' => ' Приора'],
            ['brand_id' => ' 70', 'model' => ' 3102'],
            ['brand_id' => ' 70', 'model' => ' 31105'],
            ['brand_id' => ' 70', 'model' => ' Siber'],
            ['brand_id' => ' 70', 'model' => ' Соболь'],
            ['brand_id' => ' 71', 'model' => ' Hunter'],
            ['brand_id' => ' 71', 'model' => ' Patriot'],
            ['brand_id' => ' 71', 'model' => ' Pickup']
        ];
        foreach ($cars as $item) {
            CarModels::create([
                'brand_id' => $item['brand_id'],
                'model' => $item['model']
            ]);
        }
    }
}
